highlighter: pygments
encoding: utf-8
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
gems:
    - jekyll-assets

assets:
  js_compressor: uglifier
  css_compressor: sass
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _vendors/javascripts

name: Shane Starcher

title: Resume for Shane Starcher
description: Digital resume for Shane Starcher
url: 'https://shanestarcher.com'
baseurl: ""
personal: 'https://www.shanestarcher.com'
email: shane.starcher@gmail.com
twitter: sstarcher
copyright: All rights reserved.
navigation: navigation
analytics: UA-1959564-1