title: Shane Starcher
description: Random Software Developer
texture:
  title: Shane Starcher
  tagline: Resume
  date_format: "%b %-d, %Y"
  style: black

  social_links:
    untappd: sstarcher
    github:  sstarcher
    facebook: shanestarcher
    linkedIn: us/sstarcher # format: locale/username
  analytics_id: 'UA-1959564-1'

# Build settings
theme: texture
remote_theme: thelehhman/texture

page_gen:
  - data: recipes
    template: recipe
    name: name
    dir: recipes
    extension: html
