email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
title: test
description: huh
texture:
  title: Shane Starcher
  tagline: Resume
  date_format: "%b %-d, %Y"
  style: black

  social_links:
    untappd: sstarcher
    github:  sstarcher
    facebook: shanestarcher
    linkedIn: us/sstarcher # format: locale/username
  analytics_id: 'UA-1959564-1'

# Build settings
markdown: texture
theme: texture
remote_theme: thelehhman/texture


